### ISSUE TITLE
Unable to run!

### ISSUE THREAD

**Issue by virendrasuryavanshi** [ArthurG/LeetcodePremiumScraper#1]
Can you please help me with this error as when I am running the scrape.py file leetcode login page opens and before I login to my account the py file stops running with returning the following problem in terminal.
```
Traceback (most recent call last):
  File "scrape.py", line 70, in <module>
    main()
  File "scrape.py", line 32, in main
    driver.find_element_by_id("id_login").send_keys("")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"id_login"}
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-43-generic x86_64)
```

**Comment by HeIp** [comment]
@ArthurG

**Comment by ArthurG** [comment]
Is it working now? The latest commit should make it work.

**Comment by ArthurG** [comment]
Please re-open if you still have issues
