### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Kashish001** [ArthurG/LeetcodePremiumScraper#7]
Scraper-master\scrape.py:31: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=r'./chromedriver', chrome_options=opts)
Traceback (most recent call last):
  File "c:\Users\user\Downloads\LeetcodeCompanyScraper-master\LeetcodeCompanyScraper-master\scrape.py", line 111, in <module>
    main()
  File "c:\Users\user\Downloads\LeetcodeCompanyScraper-master\LeetcodeCompanyScraper-master\scrape.py", line 31, in main
    driver = webdriver.Chrome(executable_path=r'./chromedriver', chrome_options=opts)
  File "C:\Users\userra\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\userutable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by HackrHIVE** [comment]
> Chromedriver may be out of date. Latest versions, and those specific to your operating system can be found at [https://sites.google.com/a/chromium.org/chromedriver/](https://sites.google.com/a/chromium.org/chromedriver/)

Download from there and replace with chromedriver in your directory.
